### ISSUE TITLE
GetWeights() throws errors and crashes when using X (covariates)

### ISSUE THREAD

**Issue by bang-current** [facebookincubator/GeoLift#113]
## Bug description
When trying to get the synthetic control weights I received the following error. This error message appears with or without X (covariates). 

![GeoLift-Error](https://user-images.githubusercontent.com/103457535/187793655-fff66f74-564d-4b06-ac38-6df248e2f731.png)

R crashes when inputting X (covariates). Note that all of these inputs have been working fine for `GeoLiftMarketSelection` and `GeoLiftPower` .

![GeoLift-Error2](https://user-images.githubusercontent.com/103457535/187794009-6f32c250-153f-4395-bc2d-36acec9454e3.png)

## Reproduction steps
1. Run GetWeights() without X (covariates)
2. Run GetWeights() with X (covariates) 

## Expected behavior
  I expect a list of control DMAs with the appropriate weights used to generate the synthetic control

## Additional context
  Add any other context about the problem here. (like proxy settings, network setup, overall goals, etc.)

## Session information
  Please paste the output after running `sessionInfo()` in your R session.

```R version 4.2.0 (2022-04-22)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.3.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] bigrquery_1.4.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.8.3     knitr_1.39       magrittr_2.0.3   bit_4.0.4        R6_2.5.1         rlang_1.0.2      fastmap_1.1.0    fansi_1.0.3      stringr_1.4.0    httr_1.4.3       tools_4.2.0      xfun_0.31        utf8_1.2.2       cli_3.3.0        DBI_1.1.2        htmltools_0.5.2  ellipsis_0.3.2   yaml_2.3.5       digest_0.6.29   
[20] bit64_4.0.5      assertthat_0.2.1 tibble_3.1.7     gargle_1.2.0     lifecycle_1.0.1  crayon_1.5.1     vctrs_0.4.1      fs_1.5.2         glue_1.6.2       evaluate_0.15    rmarkdown_2.14   stringi_1.7.6    compiler_4.2.0   pillar_1.7.0     jsonlite_1.8.0   pkgconfig_2.0.3 ```

**Comment by NicolasMatrices-v2** [comment]
Hi @bang-current ! Sorry for the delay on this.  Could you please share the following information so we can try to solve this issue?
- GeoLift version being used (check sessionInfo() after you imported the library):
- Picture of output of GetWeights, with using covariates and without using them:
- The values for each of the parameters you are using (COVARIATES, MARKETS[[17]], PRE_TREATMENT_END, FIXED):

Finally, this may happen because the covariates don't vary per time and location.  If the Covariate values have the same value for all locations in a single time period, the error you are seeing could come up.  Also, the "One outcome and one treatment time found..." message is not an error.

Before running any of this, I would try updating the GeoLift library to guarantee that you are using the most updated version :)

**Comment by JussanN** [comment]
Hi I'm closing this issue as it was already answered. Let us know @bang-current if you still have questions about this subject or if it was not solved yet. Thank you.
