### ISSUE TITLE
The "Location" variable needs to be a Location?

### ISSUE THREAD

**Issue by Gabrielj96** [facebookincubator/GeoLift#160]
Hi friends,

I would like to know if I can replace location variables with channel variables.

For example:

Instead: City, state or country
Actual: Media platform (Facebook Ads, Google Ads, Linkedin Ads)

So I can measure the Lift of channel instead of countries.

Thanks

**Comment by kesemadi** [comment]
Hi @Gabrielj96, I guess you are referring to the "location" in the GeoDataRead function. The general recommendation is not to change it since this modification might require adjustments in other parts of the code as well, since the existing code is designed around location. Therefore, you should carefully consider the implications of this change before implementing it.

**Comment by kesemadi** [comment]
Hi, since there are no more questions, I'm closing the issue now. :)
