### ISSUE TITLE
Usage of Covariates

### ISSUE THREAD

**Issue by ar-asur** [facebookincubator/GeoLift#168]
Hi,

I am trying to use `Geolift` to measure a test. I have treatment and control set of locations and trying to add covariates and getting the following error `Error in extract_covariates(form, unit, time, t_int, data, cov_agg): The following covariates have no variation across units: x1, x2, x3, x4 x5`. This comes from `augsynth` package and I am not able to understand the error as I checked my covariates and they do have good amount of variance. 

I do have following questions:
- Covariates I am adding to the model do vary across time but is constant across test/control. I thought these covariates (they aren't affected by treatment) along with control would help model to better predict counterfactuals. Is my understanding right?
- I don't see any example of a data set with covariates. I would like to confirm my input data structure. currently, I am passing a data frame with a time column , location column, test KPI, control KPI and covariates (same value for test/control but changes over time)

Any suggestions would be helpful, thanks!

**Comment by kesemadi** [comment]
Hi,

Covariates that do not vary across locations within the test and control groups are not helpful in predicting counterfactuals because they do not provide any additional information to distinguish between different units.
The covariates should ideally vary both across time and across units. If they only vary over time but remain constant across locations, the model cannot leverage these covariates to improve the prediction of the counterfactuals.

Regarding your second question, the covariate should be added as another column in your data input: location, time, Y, covariate

**Comment by titubs** [comment]
@kesemadi   I tried to tag you in my original Issue POST here https://github.com/facebookincubator/GeoLift/issues/199 but i dont think it worked, so I tried through an old/closed post. I hope you can help me, thanks!
