### ISSUE TITLE
Error when using tidyr 1.2.0

### ISSUE THREAD

**Issue by laresbernardo** [facebookincubator/GeoLift#33]
Hi team. Just tested with updated `tidyr` version (1.2.0) and `GeoLiftPowerFinder()` crashes with the following error:

![248925481_638002024103542_8486967006594706359_n](https://user-images.githubusercontent.com/25909073/152225859-e9efdb19-c000-470f-adbe-da66e6750e82.png)

I downgraded to 1.1.4 and it ran OK.

```
packageurl <- "http://cran.us.r-project.org/src/contrib/Archive/tidyr/tidyr_1.1.4.tar.gz"
install.packages(packageurl, repos=NULL, type="source")
```

**Comment by ArturoEsquerra** [comment]
Thanks for raising this issue Bernardo! We've confirmed that this issue is caused by `augsynth`, underlying package we leverage in GeoLift. Specifically, in v1.2.0 of tidyr `replace_na()` has been changed so that it no longer allows the type of data to change when the replacement is applied (`replace` will now always be cast to the type of data before the replacement is made).

While we work with the developers of `augsynth` to implement a fix, we recommend following your advise and downgrade `tidyr` to version 1.1.4

`packageurl <- "http://cran.us.r-project.org/src/contrib/Archive/tidyr/tidyr_1.1.4.tar.gz"`
`install.packages(packageurl, repos=NULL, type="source")`

Thanks once again!

**Comment by NicolasMatrices-v2** [comment]
Hey all, changing the packageurl bit to non-us, in case the above fails.

```
packageurl <- "https://cran.r-project.org/src/contrib/Archive/tidyr/tidyr_1.1.4.tar.gz"
install.packages(packageurl, repos=NULL, type="source")
```

**Comment by gabriele-franco** [comment]
Hi everyone, I downgraded tidyr to 1.1.4

but still gives me the same error

attaching screenshot with the package and error
<img width="1440" alt="Schermata 2022-03-25 alle 18 05 39" src="https://user-images.githubusercontent.com/94684070/160168191-d0dc0448-c897-4fca-b4e3-1b5f81c24b5f.png">

**Comment by NicolasMatrices-v2** [comment]
Hi @gabriele-franco, could you please restart your session and rerun the GeoLiftMarketSelection bit, without installing tidyr again?

If this does not work, please share the output of your sessionInfo(). Thanks

**Comment by ArturoEsquerra** [comment]
This issue has been fixed thanks to a new version of the `augsynth` package. To use GeoLift with the latest `tidyr` version, install this newest release with: `devtools::install_github("ebenmichael/augsynth"`
