### ISSUE TITLE
Errors message when running GeoLiftMarketSelection function

### ISSUE THREAD

**Issue by xybi200666** [facebookincubator/GeoLift#41]
I ran the exactly same codes of GeoLiftMarketSelection from your demo and got the following 2 error messages. 

MarketSelections <- GeoLiftMarketSelection(data = GeoTestData_PreTest,
                                          treatment_periods = c(10,15),
                                          N = c(2,3,4,5),
                                          Y_id = "Y",
                                          location_id = "location",
                                          time_id = "time",
                                          effect_size = seq(0, 0.5, 0.05),
                                          lookback_window = 1, 
                                          include_markets = c("chicago"),
                                          exclude_markets = c("honolulu"),
                                          holdout = c(0.5, 1),
                                          cpic = 7.50,
                                          budget = 100000,
                                          alpha = 0.1,
                                          Correlations = TRUE,
                                          fixed_effects = TRUE)

Error (1) When the Correlations = TRUE is included, then the error message is:
    
Error in GeoLiftMarketSelection(data = GeoTestData_PreTest, treatment_periods = c(10,  : 
     unused argument (Correlations = TRUE)

Error (2) If Correlations = TRUE is commented out, then the following error message. 

Error in rbind(temp_Markets, BestMarkets_aux[row, ]) : 
  object 'temp_Markets' not found

Please advice how to fix the errors. 

Thanks,

**Comment by ArturoEsquerra** [comment]
Hi @xybi200666, thanks for reaching out to us!

Could you provide some more information on your R session? Sharing the output from `sessionInfo()` would be great!

Thanks!
Arturo

**Comment by xybi200666** [comment]
<img width="1436" alt="Screen Shot 2022-03-07 at 3 11 44 PM" src="https://user-images.githubusercontent.com/44693571/157133929-970bf394-7981-4552-ad47-3739f63da1bf.png">


Sure, please see the code below (which are exactly the same as your demo) as well as the screenshot from R session. 

library(GeoLift)

data(GeoLift_PreTest)


GeoTestData_PreTest <- GeoDataRead(data = GeoLift_PreTest,
                                   date_id = "date",
                                   location_id = "location",
                                   Y_id = "Y",
                                   X = c(), #empty list as we have no covariates
                                   format = "yyyy-mm-dd",
                                   summary = TRUE)


head(GeoTestData_PreTest)


GeoPlot(GeoTestData_PreTest,
        Y_id = "Y",
        time_id = "time",
        location_id = "location")


MarketSelections <- GeoLiftMarketSelection(data = GeoTestData_PreTest,
                                           treatment_periods = c(10,15),
                                           N = c(2,3,4,5),
                                           Y_id = "Y",
                                           location_id = "location",
                                           time_id = "time",
                                           effect_size = seq(0, 0.5, 0.05),
                                           lookback_window = 1, 
                                           include_markets = c("chicago"),
                                           exclude_markets = c("honolulu"),
                                           holdout = c(0.5, 1),
                                           cpic = 7.50,
                                           budget = 100000,
                                           alpha = 0.1,
                                           Correlations = TRUE,
                                           fixed_effects = TRUE)




MarketSelections <- GeoLiftMarketSelection(data = GeoTestData_PreTest,
                                           treatment_periods = c(10,15),
                                           N = c(2,3,4,5),
                                           #N = 2, 
                                           Y_id = "Y",
                                           location_id = "location",
                                           time_id = "time",
                                           effect_size = seq(0, 0.5, 0.05),
                                           lookback_window = 1, 
                                           include_markets = c("chicago"),
                                           exclude_markets = c("honolulu"),
                                           holdout = c(0.5, 1),
                                           cpic = 7.50,
                                           budget = 100000,
                                           alpha = 0.1,
                                           #Correlations = TRUE,
                                           fixed_effects = TRUE)

**Comment by ArturoEsquerra** [comment]
Hi again,

Could you share your session info (the output from `sessionInfo()`?

**Comment by xybi200666** [comment]
Please see the screenshot below. 
<img width="1440" alt="Screen Shot 2022-03-07 at 5 06 43 PM" src="https://user-images.githubusercontent.com/44693571/157145506-7e99a75e-e590-4246-a67e-e59ee3bcd83a.png">

**Comment by NicolasMatrices-v2** [comment]
Hi @xybi200666 ! Could you try reinstalling the GeoLift package and upgrade to v 2.3.5 and rerunning the demo? 

remotes::install_github("facebookincubator/GeoLift")

I think that the first problem should be resolved by that (it seems to be because you are using an old version of the pkg).  

Thanks!

**Comment by xybi200666** [comment]
Thanks much for your response.
After I install the new version, in case I need to go back to the old version, can I still do that?

**Comment by NicolasMatrices-v2** [comment]
Yes, you can roll back to v2.2.2 by running `devtools::install_github("facebookincubator/GeoLift@d312c3b")` which is the last commit with this version in our repository (https://github.com/facebookincubator/GeoLift/tree/d312c3bd38d9443aebac6e509b697d6bcb97d7e4).

**Comment by NicolasMatrices-v2** [comment]
Hi @xybi200666, thanks for your question, did you restart your session after going updating to the new version? 

Please follow these steps:
- Update to new version of GeoLift v.2.3.5
- Restart your session.
- Rerun the code you provided above (import GeoLift lib, use sampled data, read it with GeoDataRead, run GeoLiftMarketSelection).
- If you have an error, its probably going to be a different error than the one before.  If that is the case, please copy and paste it here.
- If you do not have an error anymore after updating GeoLift and restarting your R session, please close this issue.

In the previous walkthrough, we chose the 15 day setup instead of the 10 day setup because:
- They have similar MDEs (10 day setup gets power higher than 90% at 9% MDE; 15 day setup gets power higher than 90% at 10-11%).
- The setup for 15 days has a smaller daily budget (around 4K per day vs 5K per day for a 10 day setup).
- Longer setups can be preferred if the turnaround of the KPI we are measuring from exposure to action is long.

**Comment by xybi200666** [comment]
@NicolasMatrices-v2   Thanks much for your response. After restarting my session, then the issue was solved. Thanks much. I will close this issue after this question. 

Can you explain a little bit about the MDEs in this package? I think the output from the GeoLiftPower function is different from my understanding about MDEs. My understanding is the smaller the MDE is, the longer time needed to run the test. But, why it is the opposite from the demo with 10 days at 9% MDE and 15 days at 10-11% MDE? 

Thanks much,

**Comment by NicolasMatrices-v2** [comment]
Hey @xybi200666.  

The MDE is an estimation based off of the dataset we have.  Because of the way in which we are running simulations, a 15 day test and a 10 day test have 10 overlapping days within the same treatment.  Hence, both setups are probably going to have similar power results.  

This is similar to what we have seen in practice, with an effect that is pretty much constant throughout time (for marketing campaigns across different media).

We suggest you take a look at the new improved walkthrough for version 2.3.5.  Things have changed quite a bit!! 

If you have further questions about the demo or about GeoLift in general, please feel free to join and post to our Facebook group https://www.facebook.com/groups/fbgeolift/.  Some of the content may interest you.  

Closing this issue as the problem has been solved by updating GeoLift to the new version.
