### ISSUE TITLE
Plot Error

### ISSUE THREAD

**Issue by ilaria-giunti** [facebookincubator/GeoLift#55]
Hi there,
where I try running plot function to find out what the results of the GeoLift() model would look like with the latest possible test period as well as the test’s power curve across all simulations.

I have this error.

Can anybody help me?

> plot(MarketSelections, market_ID = 3, print_summary = FALSE)
Messaggio di avvertimento:
Removed 26 rows containing missing values (geom_smooth).

**Comment by ArturoEsquerra** [comment]
Hi @ilaria-giunti, thanks for reaching out!

Quick question: was the plot generated despite this warning message?

For a bit of additional context, this particular warning message is usually pretty harmless and is simply pointing out that there might be some conflicts with the limit on the y axis. Nevertheless, since we specifically define the `ylim()` this shouldn't have any effect on the quality or accurateness of the plot.

**Comment by ilaria-giunti** [comment]
<img width="1438" alt="Schermata 2022-03-25 alle 20 47 27" src="https://user-images.githubusercontent.com/102374311/160191117-4b41dfd4-5b77-4f7b-8518-5e90f50d993b.png">
This is it ;)

What do you think about it?

**Comment by ArturoEsquerra** [comment]
Thanks for sharing the plot! That is the actual result we wanted to obtain from the `plot()` function. You can safely ignore those warning messages for now. We will fix the conflict with the y axis in an upcoming release so that users won't get these warning messages anymore!

**Comment by ilaria-giunti** [comment]
thank you so much!

To use it Geolift in other countries (such as EU Countries, Italy, etc.) we can just use a column in the spreadsheet with cities, or regions., cannot we?

Or do you suggest another way? We don't have DMAs

**Comment by ArturoEsquerra** [comment]
Hi again @ilaria-giunti! You can definitely use GeoLift using different levels of geo-aggregation. The most common ones are city and state-level!
