### ISSUE TITLE
Some questions regarding function design

### ISSUE THREAD

**Issue by yulisong** [facebookincubator/GeoLift#66]
Hi @NicolasMatrices-v2 @ArturoEsquerra, 

Hope you are well. 

Sorry to bother you again. I'm trying to understand how you designed this package. I believe this can help me to have a better understanding of your great work. Currently, I've got several questions, and I would be grateful if you could give me some further details.

1. I'm trying to understand the argument `run_stochastic_process=TRUE` in `stochastic_market_selector()`. I've already read the help doc but it's not very clear for me.  Could you please explain its usage a little bit further?

2. The argument `alpha` in `GeoLiftMarketSelection()` is not used in the function body. I would like to know if you plan to use it as the threshold to decide the **significant** column or it will not be used in the future?

3. Currently, I'm trying to understand the argument `lookback_window`. I know that it's used to change the learning period and test period. However, I'm not sure when we need to use it. It would be great if you could provide me some hint on why it's introduced in `GeoLiftMarketSelection()`.

4. At the start of the `GeoLiftMarketSelection()`, we are trying to find the best matching market using `MarketMatching::best_matches()`. After that, we will use some of the best matching market as the control group. I feel a little bit confused here. From my intuitive, my short working experience and **MarketMatching** package, I assume we will use the best matching market as the control group and test group separately. Would you mind telling me how you consider about the selection of control/test group?

5. When I run the demo code, I find that we will generate the same control group twice. From my humble opinion, we should run the same amount of the test for each unique control group. I was wondering if you could tell me how you decided here. 

```
     [,1]         [,2]     
[1,] "atlanta"    "chicago"
[2,] "chicago"    "atlanta"
[3,] "cincinnati" "chicago"
[4,] "portland"   "chicago"
```

6. Line 183 to 184 in the source code of `GeoLiftMarketSelection()` shows that we'll abandon one row if the absolute value of the budget is not greater than the absolute value of the investment. I'm very interested in why we use absolute value here.

I realize I've asked too many questions and appreciate any help you could provide. 

I look forward to hearing from you.

Best regards,
Yuli

**Comment by NicolasMatrices-v2** [comment]
Hey @yulisong, thanks for your questions. Answering below:

> 1. I'm trying to understand the argument run_stochastic_process=TRUE in stochastic_market_selector(). I've already read the help doc but it's not very clear for me. Could you please explain its usage a little bit further?

The GeoLiftMarketSelection will provide a ranking of the top treatment group market combinations available for a particular dataset.  When set to TRUE, the run_stochastic_process option ensures that you will get an initial random combination of treatment groups as an input to the ranking algorithm.  If set to FALSE, the input to the ranking algorithm will be provided by the first N elements of the MarketMatching::best_matches() output.  

We suggest you start by using run_stochastic_process = FALSE and if you do not find good setups, move to run_stochastic_process = TRUE.  That way, you are guaranteed to have more options and will probably be able to converge to a "local best setup" easier.

> 2. The argument alpha in GeoLiftMarketSelection() is not used in the function body. I would like to know if you plan to use it as the threshold to decide the significant column or it will not be used in the future?

I've already added another issue related to this topic to address it in our next PR. Thanks for flagging this! 

> 3. Currently, I'm trying to understand the argument lookback_window. I know that it's used to change the learning period and test period. However, I'm not sure when we need to use it. It would be great if you could provide me some hint on why it's introduced in GeoLiftMarketSelection().

The way this parameter works is that it defines the amount of simulations that will be run over each treatment group combination.  In essence, what we are doing is applying the same effect for a different treatment period (with the same duration) and using a reduced pre-treatment period to calculate the counterfactual.  Here's a pic that I hope explains this more clearly.
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/62114243/163846144-697e0c58-b1bd-4aa1-9264-847829d8ad94.png">

Since GeoLiftMarketSelection runs over all the treatment combinations, we suggest you use lookback_window = 1 to get a proxy of best ranked treatments.  Then, we suggest you use GeoLiftPower to get the power curve for the top 5 treatments, with a larger lookback_window, to ensure that you have a more robust result over different time periods.  Finally, plot these out using plot(GeoLiftPower_output) to observe the shape of the power curve.  That way you get a global scope of the problem, and you deep dive into the treatment combinations that are worth it. 

While you can use a larger lookback_window within GeoLiftMarketSelection, we do not recommend it given the time constraint on the algorithm.  It's there in case you would like to do both of these steps in one single run.

> 4. At the start of the GeoLiftMarketSelection(), we are trying to find the best matching market using MarketMatching::best_matches(). After that, we will use some of the best matching market as the control group. I feel a little bit confused here. From my intuitive, my short working experience and MarketMatching package, I assume we will use the best matching market as the control group and test group separately. Would you mind telling me how you consider about the selection of control/test group?

The MarketMatching::best_matches()$BestMatches method will output a m:m mapping between all locations (id_variable) within the data, sorted by the correlation between each location throughout time. We are using that to get the most correlated geographical units to each location.

Basically, what we are doing here is selecting the best matching markets to be part of the same group (i.e. Treatment).  We want to ensure that the locations that are within the same group has as similar a trend as possible, to ensure that while we are finding a good synthetic control to the entire treatment group, our fit to each particular location is also as good.  If controls from the donor pool aren't similar, we risk interpolation bias (further details in this paper, page 409  https://economics.mit.edu/files/17847).

> 5. When I run the demo code, I find that we will generate the same control group twice. From my humble opinion, we should run the same amount of the test for each unique control group. I was wondering if you could tell me how you decided here.

This should be solved by passing the the output of stochastic_market_selector that uses the BestMarkets object as an input.  In any case, could you share a minimum working example so I can reproduce?

> 6. Line 183 to 184 in the source code of GeoLiftMarketSelection() shows that we'll abandon one row if the absolute value of the budget is not greater than the absolute value of the investment. I'm very interested in why we use absolute value here. 

Basically, this has to do with the fact that we will not return setups that require an investment that is higher than the budget the user has for the test.  

It is useful for users that want to run a test and know:
- how much their Expected Cost Per Incremental KPI is.
- how much budget they have for the test.

With these two variables, it makes sense to filter out the combinations that have an investment above the test budget, because they are not feasible (this is the Walkthrough case).  However, if this is NOT your use case, then we suggest you leave the budget with NULL.

Let me know if these answers make sense.  Happy to follow up on your point 5 after you've provided the code :) Thanks!

**Comment by NicolasMatrices-v2** [comment]
@yulisong point 2. was addressed in this PR https://github.com/facebookincubator/GeoLift/pull/68

**Comment by NicolasMatrices-v2** [comment]
Hi Yuli, following up on your points.

> 1. run_stochastic_process = TRUE

Not sure I understand what you mean.  Since the selection is random, and when you select a treatment group order does not matter, then the "standard" markets are interchangeable.  Hence, when you run this process, the chances that you will chose all standard markets in some combination of treatment group is high.  

To prove my point, take a look at the following snippet.  It builds a random similarity_matrix of size total_elements and runs 10K simulations were the stochastic process is run over the matrix.  At the end, it outputs the amount of unique elements that were part of at least 1 simulation.  Even for low treatment_sizes (i.e. 2), the count returns a high likelihood of including all markets within the majority of the simulations.  When the treatment size is higher, the chance of including all markets within the treatment group increases drastically (which is good for our purposes).  Let me know your thoughts.

```
library(dplyr)
library(GeoLift)

# Build similarity square matrix with random correlations
total_elements <- 20
l <- letters[1:total_elements]
all_rows <- c()
for (i in 1:total_elements){
  new_row <- c(l[i], sample(l[l != l[i]]))
  # similarity_matrix <- rbind(similarity_matrix, new_row)
  all_rows <- rbind(all_rows, new_row)
}
similarity_matrix <- matrix(all_rows, ncol=total_elements, nrow=total_elements)

# Simulate different iterations of stochastic selection.
unique_elements <- c()
sim_count <- 10000
for (i in 1:sim_count){
  stochastic_iteration <- suppressMessages(
    stochastic_market_selector(
      treatment_size = 1,
      similarity_matrix = similarity_matrix,
      run_stochastic_process = TRUE)
  )
  unique_elements <- c(unique_elements, nrow(unique(matrix(stochastic_iteration))))
}

table(unique_elements)
```

> 3. lookback_window

Maybe I was not clear.  
- When we run the experiment analysis, after the experiment has finished, we will not exclude any periods from the pre-treatment period.  We will use everything until the last day before the treatment.
- When we run the power analysis before the experiment, we can chose to run more than 1 simulation with different effect sizes for each treatment by expanding the lookback_window.  The way those simulations are run is with the picture I showed you above.  What we want to do in this case is have a more robust estimate of the metrics for each treatment setup, to observe if the same behavior occurs across different simulated testing and pre-treatment periods.  The intuitive idea here is that we want to capture some of the variability in the time series in our test setups, to avoid specifying something that could be different in the future.

> 5. repeated treatment combinations.

Thank you for highlighting this! I will work on a PR to address this and link to this issue as well.  Should be an easy fix.

**Comment by yulisong** [comment]
Hi @NicolasMatrices-v2, 

Thank you for your reply! Your explanation on my third question is very clear, and I understand it now. I can feel this package has been well designed by you and other contributors. 

I understand what you mean on question 1 now. However, I think my expression is very bad and I would like to explain my question again. Considering it's the market of the **first** column inside similarity_matrix rather than the market of the **second** column that has DTW similarity with the rest of market, we should always select the market of the first column with some other markets rather than sometimes selecting the market of the second column with some other markets.

Sorry for my confusing expression. Hope my explanation this time can help you understand my question.

**Comment by NicolasMatrices-v2** [comment]
closed out point 5 with the PR we just merged. Feel free to download and upgrade to v2.4.22

**Comment by NicolasMatrices-v2** [comment]
Hi @yulisong ! 

Ok, I understand your Q better, thanks for the clarification! 

If you take a look at the example I provided, the first column inside similarity_matrix will be captured in the majority of the simulations with N = 2, given that treatment locations are interchangeable within the treatment group, so I think we are good on that front.  Also, being a stochastic process, we would like to give some randomness to the selection of locations for each treatment, and we think that this is achieved by not fixing the first column from similarity_matrix.  

Best!

**Comment by yulisong** [comment]
Hi @NicolasMatrices-v2, 

Thank you for your comment on this question. I understand your thoughts here after your clear explanation. I'll close this issue now.
