### ISSUE TITLE
varying level of treatment over time

### ISSUE THREAD

**Issue by stefanoallima** [facebookincubator/GeoLift#73]
Hi all,
thanks for the great package.
The company i work for is a B2B so during the week-end and bank holidays business users are less active and media reach of business users is lower.

In the scenario of the treatment being "paused" (the "pause" might be a true pause in media treatment or due to a significant reach drop due to characteristic of the media & target under experimentation) for example during a bank holiday or the week end... or long week-ends and these happening during the experiment treatment period.
Do you have any recommendation on handling these scenarios?

**Comment by NicolasMatrices-v2** [comment]
Hi @stefanoallima ! Sorry for not replying sooner to your issue.

I think its worth making a distinction between these two cases: turning the treatment on and off during the treatment period and a treatment with some degree of weekly seasonality.

For the case of a treatment with weekly seasonality, where the user does not manually change something and the campaign evolves as expected (large audience on weekdays, low audience on weekends), I suggest you leave as is.  This is Business As Usual for the campaign, given the nature of your B2B business.  When we run these types of experiments, we would like to be able to measure what would happen in a normal scenario without the ongoing experiment, to make results as relatable to normal circumstances as possible.

For the case where you turn a treatment on and off during a treatment period, because for example no sales happen during weekends and campaigns are paused, then you could exclude these days from the analysis.  But if you do so, I would exclude all weekends from the series, given that sales for all regions are zero on those days.  If that is not the case, and you have some regions that had sales and some that didn't on weekends, I would keep the series as is, given that not all locations behave the same in your dataset.

Closing this issue for now.  Feel free to reopen if you have further comments.
