### ISSUE TITLE
Get confidence intervals

### ISSUE THREAD

**Issue by max-kozlowski** [facebookincubator/GeoLift#76]
## Is your feature request related to a problem? Please describe.
Aside from p-value, it would be great to also get some confidence intervals  of the lift measured (such as upper/lower bounds at 95% confidence for example) as a part of summary.

## Describe alternatives you've considered
I could calculate it manually but it would be much nicer to just have a function for this. In the meantime - would you happen to know a formula in R that could do the calculation for me?

**Comment by ArturoEsquerra** [comment]
Hi @max-kozlowski! While you can currently obtain a CI estimate in GeoLift by setting the `ConfidenceIntervals` to `ConfidenceIntervals = TRUE`, this estimate comes from a different methodology than the p-values. Specifically, while we use conformal inference to obtain the p-values, the confidence intervals when `ConfidenceIntervals = TRUE` are currently being calculated through a jackknifing+ approach which unfortunately can cause some discrepancies between them. We'll consolidate the CI's in a future release so that they are calculated with the same methodology as the p-values

**Comment by max-kozlowski** [comment]
Thank you @ArturoEsquerra! I wonder if I could try to manually calculate CI's using conformal inference so that it's the method as p-values. Would you happen to have some pieces of code that could help with this?
