### ISSUE TITLE
Adv Spent in the past 

### ISSUE THREAD

**Issue by ilaria-giunti** [facebookincubator/GeoLift#91]
## Bug description
Could I set the amount of spending in the past to take into consideration this value for the investment?
Or how can I put the seasonality and other variables in covariates?

## Session information
  Please paste the output after running `sessionInfo()` in your R session.

## Reproduction steps
  Enter steps to reproduce the behavior.

## Expected behavior
  Give a clear and concise description of what you expected to happen.
  
```
Output goes here
```

## Additional context
  Add any other context about the problem here. (like proxy settings, network setup, overall goals, etc.)

**Comment by Tsurty** [comment]
I'll add on this one because I'd like to understand based on what data, GeoLift suggests a specific budget.

There's an input field for "budget" that you are willing to spend and it makes sense.
GeoLift won't have data on the spending per region but it will probably match that up based on the sales patterns.

In the case I don't specify any budget, how does the process work? How would I know if that output budget applies to me or if it's too low/high?

**Comment by ArturoEsquerra** [comment]
Hi @ilaria-giunti and @Tsurty! 

The concepts behind the `budget` parameter and more generally the investment is to measure how large the intervention should be. That is, how much incremental spending we need in the test regions in order to obtain a significant Lift given a certain `cpic`. With this in mind, the previous spending isn't directly part of the model as we are focusing on incrementality compared to the counterfactual.

For example, let's assume we want to measure the incremental impact of video campaigns on top of our Business As Usual (static ads). In other words, the intervention is the implementation of video. Here, we would provide a `cpic` associated with video campaigns to `GeoLiftMarketSelection()` in order to obtain the budget we will need for these campaigns. This investment will help us reliably find an incremental effect compared to the baseline (BAU only). Therefore, since GeoLift focuses on measuring the intervention, it doesn't directly consider the spending on the baseline/BAU.

Finally, providing a budget isn't **absolutely necessary** for GeoLift tests. Nevertheless, without controlling the budget we have less control over which tests will come out significant or not. We would have to wait and see if the effect was large enough to provide significant results.
