### ISSUE TITLE
Lift Understanding for control group

### ISSUE THREAD

**Issue by roh-neenopal** [facebookincubator/GeoLift#93]
## Bug description
The model has suggested me to run ads in 3 cities and have 'x'  value as incremental Y for 15 days. If, the results are similar when the ads are run in those cities - what conclusion should I make? Should I then be running the same advertisement in my control group as well where initially the advertisements were not executed? Does, it mean if I run the same advertisement in the rest of the cities I would be getting a similar lift?

## Reproduction steps
  Enter steps to reproduce the behavior.

## Expected behavior
  Give a clear and concise description of what you expected to happen.
  
```
Output goes here
```

## Additional context
  Add any other context about the problem here. (like proxy settings, network setup, overall goals, etc.)

**Comment by ArturoEsquerra** [comment]
Hi @roh-neenopal! Could you expand a bit of this scenario?

GeoLift works by analyzing the incremental effect of an intervention (generally running ads). Therefore, if the GeoLift model suggested running ads in 3 locations for 15 days, we wouldn't run ads on the control locations for the same duration. This will allow us to create a counterfactual and measure what was the true Lift of those ads. [Inverse Geolifts](https://facebookincubator.github.io/GeoLift/blog/inverse-geolift) are a great alternative when you want to have small holdouts!

**Comment by roh-neenopal** [comment]
So, the situation is as follows:-

Let's say that Geolift suggests that you should add City A, B and C in your test group for 15 days and you will get an incremental Y = 5000. In real-world, we conduct the same. Now, lets suppose there are three scenarios : A - Increment Y is 5000; B - Increment Y is 10,000 and C - Increment Y is 10. What conclusions can I make in all three scenarios.  If the expected increment Y is similar to real Increment Y - what should we do then? Should I also make the new changes in my control group too

**Comment by roh-neenopal** [comment]
If my expect lift is same as real-lift for an ad. What should be my next steps? Is it safe to say, that now since I know the lift for an ad through the treatment group - now I can run the ad in my control group as-well?

**Comment by NicolasMatrices-v2** [comment]
Hi @roh-neenopal! 

So, simplifying it, there are two moments in GeoLift: one is before the test, the other is after the test.

Before the test, you will run the power module of GeoLift and select which are the best locations to build your treatment.  Along with other metrics, this will give you the Minimum Detectable Effect (this is what you are referring to as "expect lift").  This is the smallest effect size that we will be able to detect with sufficient confidence in our result.  If it is 5% for example, it means that if the real effect is below 5% (2%) we probably will not be able to observe it with high confidence.

After the test, you run the post-test analysis module that evaluates what the real effect of the treatment is.  So, the MDE and the real lift are independent, the MDE is just one of the metrics we use to signal if your treatment group can work for your particular dataset.

Going to your last question, after the test, GeoLift will tell you the effect of applying the treatment on the treatment group.  This can also tell you what is the Cost Per Incremental Conversion of running your treatment.  This can be used to calibrate attribution models or to have a general idea of how much each conversion influenced by this media cost you.  At this point in time, you should decide on thinking about new hypothesis of things to test.  If you don't want to do any more tests, its safe to show media to the entire country again, since the experiment has finished.

Related to your first question, as @ArturoEsquerra mentioned, GeoLift will give you the aggregate effect for the treatment in the treatment group.  Therefore, you cannot split the incremental between A, B & C, you can only see the effect for A+B+C since this is what the expeirment was built for.  If you would like to get the incremental for each separate city, you would have to build three different GeoLift experiments.
