### ISSUE TITLE
Understanding the output

### ISSUE THREAD

**Issue by roh-neenopal** [facebookincubator/GeoLift#94]
## Bug description
I have been playing around with Geolift. When CPIC is 500 and budget is 10,000 - We get result-A. When CPIC is 500 and budget is 1- We get Result B. When CPIC is 500 and budget is 1000 - We get Result C. How do we interpet these results?
## Session information
GeoLift Results Summary

##################################
##################################

* Average ATT: 0.096
* Percent Lift: 5%
* Incremental Y: 4
* P-value: 0.03

##################################
##################################

* L2 Imbalance: 8.589
* Scaled L2 Imbalance: 0.8488
* Percent improvement from naive model: 15.12%
* Average Estimated Bias: NA

##################################
##################################

GeoLift Results Summary

##################################
##################################

* Average ATT: 0.096
* Percent Lift: 5%
* Incremental Y: 4
* P-value: 0.03

##################################
##################################

* L2 Imbalance: 8.589
* Scaled L2 Imbalance: 0.8488
* Percent improvement from naive model: 15.12%
* Average Estimated Bias: NA

##################################
##################################

* Average ATT: 0.077
* Percent Lift: 6.3%
* Incremental Y: 2
* P-value: 0.07

##################################
##################################

* L2 Imbalance: 7.813
* Scaled L2 Imbalance: 0.8486
* Percent improvement from naive model: 15.14%
* Average Estimated Bias: NA

## Reproduction steps
  Enter steps to reproduce the behavior.

## Expected behavior
The Lift is same when Budget is 10,000 and 1. It changes when budget is 1  
```
Output goes here
```

## Additional context
  Add any other context about the problem here. (like proxy settings, network setup, overall goals, etc.)

**Comment by ArturoEsquerra** [comment]
Hi @roh-neenopal are you referring to the 'cpic' and `budget` parameters of `GeoLiftMarketSelection()`?

**Comment by roh-neenopal** [comment]
Yes, in the GeoLiftMarketSelection()

**Comment by roh-neenopal** [comment]
This is also the following graph : 
![image](https://user-images.githubusercontent.com/90190987/177608281-30cb0a7f-a645-441b-9117-a19e1e348732.png)

The Power curve is a straight line

**Comment by ArturoEsquerra** [comment]
Hi @roh-neenopal! `budget` parameter simply works as a filter to make sure all of the markets presented in the `GeoLiftMarketSelection()` output are feasible given your budget constraint. Specifically, we will check whether the `Investment` needed for each test is lower than your specified `budget`. We calculate the `Investment` column based on the `cpic` parameter by calculating how many incremental conversions are needed in order to find a significant effect (basically, #incremental_conversions * cpic). Therefore, by changing the `budget` and `cpic` you're basically looking at completely different tests (a large cpic and small budget means you can only afford small tests while having large budgets and small cpic's means that larger tests are feasible)!

Moreover, looking at your plot it seems like there was a change in the structure of the test's time-series around time-stamp ~150. If this is the case, the previous historical data will probably provide very little useful information to predict current values of the KPI.
