### ISSUE TITLE
P-Value less 95% even if i say 1 in MarketSelection

### ISSUE THREAD

**Issue by ilaria-giunti** [facebookincubator/GeoLift#96]
## Bug description
Sometimes P-Value is less than 95% even if in the MarketSelection is 1. Why? How can I solve this issue?

<img width="628" alt="Schermata 2022-07-06 alle 20 21 21" src="https://user-images.githubusercontent.com/102374311/177617244-e9c57658-d0e5-4dea-a56f-6d004eb4ad52.png">

**Comment by ilaria-giunti** [comment]
Sometimes we have a Power 1 in this table but then when I print the summary the P-Value is less than 0.95 or greater than 0.05, why is it happening?

**Comment by ArturoEsquerra** [comment]
Hi @ilaria-giunti! That's the expected behavior, the algorithm will assess whether the simulation's p-value is smaller than the specified `alpha` parameter to rule it as having enough power or not. The `power` column will show the average of these simulations. If there was only one simulation and the p-value for a given effect size and duration is smaller than the `alpha` (0.1 by default), you'll see that the power was 1.
