### ISSUE TITLE
increase budget of a campaign and covariates

### ISSUE THREAD

**Issue by ilaria-giunti** [facebookincubator/GeoLift#99]
## Bug description
- What type of covariates can I use in GeoLift? Can I have an example of the value to set?

- If I want just to say the lift of a campaign if I increase the budget, how should I set the MarketSelection?

## Expected behavior
  Give a clear and concise description of what you expected to happen.
  
```
Output goes here
```

## Additional context
  Add any other context about the problem here. (like proxy settings, network setup, overall goals, etc.)

**Comment by ArturoEsquerra** [comment]
Hi @ilaria-giunti!

Thanks for your patience while waiting for our response!

You can use any type of variable that have predicting power explaining the dependent variable. In general, we have seen good results when using variables that reflect: pricing, promotions, distribution, and media execution. We are currently working (among other things) on a blogpost on covariates, so we will have additional guidance on this area ready soon!

Regarding your second point, would you mind elaborating a little bit more on this situation?

Thanks,
Arturo

**Comment by adrialuzllompart** [comment]
@ArturoEsquerra Any chance I could get a sneak peek at that covariates blogpost? I'm currently working on a project that is very time sensitive and I could really use some more guidance on adding covariates to a GeoLift model.

I've tried adding an indicator flag to the data (1 when the observation is in the summer, 0 otherwise) but R is crashing right when I run `GeoLift()`.

**Comment by Th3Bust3r** [comment]
Would previous year be a viable covariate? For example if we had business sales by day & DMA for the past two years. Could something like "last year comps" serve as a covariate for this year's sales, since seasonal patterns are likely to be similar?

**Comment by ArturoEsquerra** [comment]
> @ArturoEsquerra Any chance I could get a sneak peek at that covariates blogpost? I'm currently working on a project that is very time sensitive and I could really use some more guidance on adding covariates to a GeoLift model.
> 
> I've tried adding a dummy covariate (an indicator variable that is 1 when the observation is in the summer and 0 otherwise) but R is crashing right when I run `GeoLift()`.

Hi @adrialuzllompart, sorry for the delay in my response! When using covariates always make sure that there is variance between them at each time-stamp. For instance, if all dummy variables are equal to zero for any given T, then the R session can potentially crash due to errors caused by singular matrices.

**Comment by ArturoEsquerra** [comment]
> Would previous year be a viable covariate? For example if we had business sales by day & DMA for the past two years. Could something like "last year comps" serve as a covariate for this year's sales, since seasonal patterns are likely to be similar?

Hi @Th3Bust3r! That is an interesting question. As long as the covariate has good predictive capabilities over our KPI, it can be used as a covariate. The one thing that might be tricky about using the previous years data is to figure out whether there is a temporal delay between comp and the KPI (maybe there is a certain lag between the comp and its effect on sales).
